import React, { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io, type Socket } from 'socket.io-client';
import { BookOpen, Bot, Check, ChevronRight, Copy, Crown, Droplets, LogOut, MessageCircle, Plus, Settings, ShieldCheck, Sparkles, Trash2, UserPlus, Users, Volume2, X } from 'lucide-react';
import './styles.css';
import './responsive.css';
import './ui-upgrade.css';
import './foundation.css';
import './wallet.css';
import './bloodyjack.css';
import './hybrid-table.css';
const BloodyTable3D=lazy(()=>import('./BloodyTable3D'));

type Suit = '♠' | '♥' | '♦' | '♣';
type Card = { suit: Suit; rank: string; hidden?: boolean };
type Phase = 'betting' | 'playing' | 'result';
type GameMode = 'classic' | 'blood-duel';
type Panel = null | 'friends' | 'settings' | 'admin' | 'invite' | 'rules' | 'profile' | 'bloodLobby' | 'onlineLobby';
type BotPlayer = { id: number; name: string; balance: number; initials: string; color: string; hand: Card[]; blood: number };
type ChatMessage = { name: string; text: string; mine?: boolean };
type User = { id:number; username:string; email:string; role:'user'|'admin' };
type PlayerStats = {hands:number;wins:number;losses:number;pushes:number;blackjacks:number;total_wagered:number;gross_winnings:number;biggest_win:number;balance:number;net_profit:number;win_rate:number};
type AdminUser = {id:number;username:string;email:string;role:string;balance:number;hands:number;wins:number;losses:number;gross_winnings:number;total_wagered:number};
type RoomPlayer = {id:number;username:string;ready:boolean;online:boolean};
type LiveRoom = {code:string;leaderId:number;status:'lobby'|'playing';players:RoomPlayer[]};
type OnlineGame = {phase:'playing'|'result';activePlayerId:number|null;dealer:Card[];players:{id:number;username:string;hand:Card[];total:number;status:string;result?:string}[];message:string};

const suits: Suit[] = ['♠', '♥', '♦', '♣'];
const ranks = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'];
const chips = [10, 25, 50, 100, 500];
const botNames = ['Luna', 'Atlas', 'Raven', 'Nova', 'Mert', 'Ace'];
const themes = { blood: ['#32050d', '#ff314b'], crimson: ['#56101c', '#ff6a78'], midnight: ['#17151b', '#c2b4c8'] };

function freshDeck() { return suits.flatMap((suit) => ranks.map((rank) => ({ suit, rank }))).sort(() => Math.random() - .5); }
function handValue(cards: Card[]) { let value=0, aces=0; cards.filter(c=>!c.hidden).forEach(({rank})=>{ if(rank==='A'){value+=11;aces++} else value+=['J','Q','K'].includes(rank)?10:Number(rank)}); while(value>21&&aces){value-=10;aces--} return value; }
function randomHand(): Card[] { const d=freshDeck(); return [d.pop()!,d.pop()!]; }
function isSoft(cards:Card[]){const raw=cards.reduce((sum,c)=>sum+(c.rank==='A'?11:['J','Q','K'].includes(c.rank)?10:Number(c.rank)),0);return cards.some(c=>c.rank==='A')&&raw===handValue(cards)}
function botShouldHit(cards:Card[],dealerCard:Card){const total=handValue(cards);const dealerValue=dealerCard.rank==='A'?11:['J','Q','K'].includes(dealerCard.rank)?10:Number(dealerCard.rank);if(isSoft(cards))return total<18;if(total<=11)return true;if(total>=17)return false;if(total===12)return dealerValue<4||dealerValue>6;return dealerValue<2||dealerValue>6}
function playSound(kind:'chip'|'card'|'turn'|'win'|'lose',enabled:boolean){if(!enabled)return;try{const AudioCtx=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;const ctx=new AudioCtx();const osc=ctx.createOscillator(),gain=ctx.createGain();const map={chip:[520,.055],card:[230,.07],turn:[740,.16],win:[880,.28],lose:[150,.25]} as const;osc.frequency.value=map[kind][0];osc.type=kind==='lose'?'sawtooth':'sine';gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.11,ctx.currentTime+.012);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+map[kind][1]);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+map[kind][1]+.02)}catch{/* Ses desteği olmayan tarayıcıda sessiz devam et. */}}

function PlayingCard({card,index=0,mini=false}:{card:Card;index?:number;mini?:boolean}) {
  if(card.hidden) return <div className={`card card-back ${mini?'mini-card':''}`} style={{'--i':index} as React.CSSProperties}><span>B</span></div>;
  const red=card.suit==='♥'||card.suit==='♦';
  return <div className={`card glow-card ${red?'red':''} ${mini?'mini-card':''}`} style={{'--i':index} as React.CSSProperties}><div className="card-corner"><b>{card.rank}</b><span>{card.suit}</span></div><div className="card-suit">{card.suit}</div><div className="card-corner card-corner-bottom"><b>{card.rank}</b><span>{card.suit}</span></div></div>;
}

function PlayerSeat({bot,onRemove,playing,active,bloodMode}:{bot:BotPlayer;onRemove:()=>void;playing:boolean;active:boolean;bloodMode:boolean}) {
  return <div className="rival-player">
    {playing&&<div className="rival-hand">{bot.hand.map((c,i)=><PlayingCard card={c} index={i} mini key={i}/>)}<b>{handValue(bot.hand)}</b></div>}
    <div className={`seat glass-seat ${active?'active-turn':''} ${bot.blood<=0?'bloodless':''}`}><div className="avatar" style={{background:bot.color}}>{bot.initials}</div><div><strong>{bot.name}<small> BOT</small></strong><span><i/> {bot.balance.toLocaleString('tr-TR')}</span>{bloodMode&&<div className="blood-meter"><i style={{width:`${bot.blood}%`}}/><b>{bot.blood>0?`${bot.blood} KAN`:'KANSIZ'}</b></div>}</div><button className="remove-bot" title="Botu kaldır" onClick={onRemove}><X/></button></div>
  </div>;
}

function Modal({title,icon,close,children}:{title:string;icon:React.ReactNode;close:()=>void;children:React.ReactNode}) {
  return <div className="modal-layer" onMouseDown={close}><section className="modal glass-panel" onMouseDown={e=>e.stopPropagation()}><header className="modal-head"><div>{icon}<span>{title}</span></div><button onClick={close}><X/></button></header>{children}</section></div>;
}

function Auth({onLogin}:{onLogin:(user:User)=>void}) {
  const adminLogin=new URLSearchParams(location.search).get('admin')==='1';const [name,setName]=useState('');const [email,setEmail]=useState('');const [pass,setPass]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  const submit=async()=>{setError('');setLoading(true);try{const response=await fetch(`/api/auth/${adminLogin?'login':'guest'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(adminLogin?{email,password:pass}:{username:name})});const data=await response.json();if(!response.ok)throw new Error(data.error);onLogin(data.user)}catch(e){setError(e instanceof Error?e.message:'Bağlantı hatası.')}finally{setLoading(false)}};
  return <div className="auth-page"><div className="auth-orb one"/><div className="auth-orb two"/><section className="auth-card glass-panel"><div className="auth-logo"><Crown/><b>BLOODYJACK</b><span>PRIVATE BLACKJACK CLUB</span></div><h1>{adminLogin?'Yönetici girişi':'Masaya katıl'}</h1><p>{adminLogin?'BloodyJack yönetim hesabınla giriş yap.':'Takma adını seç, masanı kur veya arkadaşının davetine katıl.'}</p>{adminLogin?<><label>E-POSTA<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="ornek@mail.com" type="email"/></label><label>ŞİFRE<input value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder="En az 8 karakter" type="password"/></label></>:<label>TAKMA ADIN<input autoFocus maxLength={18} value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&name.trim().length>=2&&submit()} placeholder="Örn. BloodyEmir"/></label>}{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" onClick={submit} disabled={loading||(adminLogin?(!email||pass.length<8):name.trim().length<2)}>{loading?'BAĞLANIYOR...':adminLogin?'ADMİN GİRİŞİ':'NİCK İLE KATIL'}<ChevronRight/></button><small className="demo-note">Ücretsiz sanal jeton • Gerçek para kullanılmaz</small></section></div>;
}

function App(){
  const [user,setUser]=useState<User|null>(null),[authLoading,setAuthLoading]=useState(true);
  const [balance,setBalance]=useState(2500),[bet,setBet]=useState(0),[phase,setPhase]=useState<Phase>('betting');
  const [deck,setDeck]=useState<Card[]>(freshDeck()),[player,setPlayer]=useState<Card[]>([]),[dealer,setDealer]=useState<Card[]>([]),[message,setMessage]=useState('BAHİSLERİNİZİ YERLEŞTİRİN');
  const [turnOwner,setTurnOwner]=useState<number|'player'|null>(null);
  const [splitHand,setSplitHand]=useState<Card[]|null>(null),[activeHand,setActiveHand]=useState(0),[handBets,setHandBets]=useState<number[]>([]),[insuranceOffer,setInsuranceOffer]=useState(false),[insuranceDelta,setInsuranceDelta]=useState(0);
  const [bots,setBots]=useState<BotPlayer[]>([{id:1,name:'Mert',balance:148000,initials:'M',color:'linear-gradient(145deg,#b96242,#462116)',hand:randomHand(),blood:100},{id:2,name:'Nova',balance:126000,initials:'N',color:'linear-gradient(145deg,#5f88a8,#172c3d)',hand:randomHand(),blood:100}]);
  const [gameMode,setGameMode]=useState<GameMode>('classic'),[playerBlood,setPlayerBlood]=useState(100);
  const [duelStake,setDuelStake]=useState(0),[prizePool,setPrizePool]=useState(0),[duelActive,setDuelActive]=useState(false),[duelBusy,setDuelBusy]=useState(false),[duelError,setDuelError]=useState('');
  const socketRef=useRef<Socket|null>(null);const [liveRoom,setLiveRoom]=useState<LiveRoom|null>(null),[onlineGame,setOnlineGame]=useState<OnlineGame|null>(null),[roomCodeInput,setRoomCodeInput]=useState(''),[roomError,setRoomError]=useState(''),[roomBusy,setRoomBusy]=useState(false);
  const [panel,setPanel]=useState<Panel>(null),[theme,setTheme]=useState<keyof typeof themes>('blood'),[sound,setSound]=useState(true),[effects,setEffects]=useState(true);
  const [chatOpen,setChatOpen]=useState(true);
  const [messages,setMessages]=useState<ChatMessage[]>([{name:'Mert',text:'Bol şans millet 👋'},{name:'Nova',text:'Bu el benim.'}]),[chat,setChat]=useState('');
  const [copied,setCopied]=useState(false);
  const [nextRewardAt,setNextRewardAt]=useState(0),[now,setNow]=useState(Date.now()),[rewardBusy,setRewardBusy]=useState(false),[stats,setStats]=useState<PlayerStats|null>(null),[adminUsers,setAdminUsers]=useState<AdminUser[]>([]),[adjustUser,setAdjustUser]=useState<AdminUser|null>(null),[adjustAmount,setAdjustAmount]=useState(''),[adjustReason,setAdjustReason]=useState('');
  useEffect(()=>{fetch('/api/auth/me').then(r=>r.ok?r.json():Promise.reject()).then(d=>setUser(d.user)).catch(()=>setUser(null)).finally(()=>setAuthLoading(false))},[]);
  useEffect(()=>{if(turnOwner==='player'){playSound('turn',sound)}},[turnOwner,sound]);
  useEffect(()=>{if(!user)return;fetch('/api/wallet').then(r=>r.json()).then(d=>{if(typeof d.balance==='number')setBalance(d.balance);if(d.nextRewardAt)setNextRewardAt(d.nextRewardAt)});fetch('/api/stats').then(r=>r.json()).then(d=>d.stats&&setStats(d.stats))},[user]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(panel==='admin'&&user?.role==='admin')fetch('/api/admin/users').then(r=>r.json()).then(d=>setAdminUsers(d.users||[]))},[panel,user]);
  useEffect(()=>{if(!user)return;const invited=new URLSearchParams(location.search).get('room')?.toUpperCase();const socket=io({withCredentials:true,reconnection:true});socketRef.current=socket;socket.on('room:update',(room:LiveRoom)=>setLiveRoom(room));socket.on('room:started',(room:LiveRoom)=>{setLiveRoom(room);setPanel(null);setMessage('ONLINE MASA BAŞLADI')});socket.on('game:update',(game:OnlineGame)=>setOnlineGame(game));socket.on('connect',()=>{setRoomError('');if(invited)socket.emit('room:join',{code:invited},(reply:{ok:boolean;error?:string;room?:LiveRoom})=>{if(reply.ok&&reply.room){setLiveRoom(reply.room);setPanel('onlineLobby')}else setRoomError(reply.error||'Masa bulunamadı.')})});socket.on('connect_error',()=>setRoomError('Canlı masa sunucusuna bağlanılamadı.'));if(invited){setRoomCodeInput(invited);setPanel('onlineLobby')}return()=>{socket.disconnect();socketRef.current=null}},[user]);
  useEffect(()=>{if(!user||!onlineGame)return;const mine=onlineGame.players.find(p=>p.id===user.id);if(!mine)return;setPlayer(mine.hand);setSplitHand(null);setDealer(onlineGame.dealer);setPhase(onlineGame.phase);setTurnOwner(onlineGame.activePlayerId===user.id?'player':onlineGame.activePlayerId);setMessage(onlineGame.phase==='result'?`${mine.result||''} • ${onlineGame.message}`:onlineGame.message);setBots(onlineGame.players.filter(p=>p.id!==user.id).map((p,i)=>({id:p.id,name:p.username,balance:0,initials:p.username[0].toUpperCase(),color:`linear-gradient(145deg,hsl(${(i*83+350)%360} 55% 48%),#251018)`,hand:p.hand,blood:100})))},[onlineGame,user]);
  const playerValue=useMemo(()=>handValue(player),[player]),splitValue=useMemo(()=>splitHand?handValue(splitHand):0,[splitHand]),dealerValue=useMemo(()=>handValue(dealer),[dealer]); const colors=themes[theme];
  if(authLoading) return <div className="auth-page"><div className="loading-mark"><Crown/><span>BLOODYJACK</span></div></div>;
  if(!user) return <Auth onLogin={setUser}/>;

  const addBet=(amount:number)=>{if(phase==='betting'&&amount<=balance-bet){playSound('chip',sound);setBet(v=>v+amount)}};
  const recordGame=async(delta:number,result:'win'|'loss'|'push',blackjack=false)=>{const response=await fetch('/api/game/result',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wager:bet,delta,result,blackjack})});const data=await response.json();if(response.ok&&typeof data.balance==='number')setBalance(data.balance);fetch('/api/stats').then(r=>r.json()).then(d=>d.stats&&setStats(d.stats))};
  const settleBloodDuel=async(won:boolean)=>{if(!duelActive)return;setDuelActive(false);const response=await fetch('/api/blood-duel/settle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({won})});const data=await response.json();if(response.ok&&typeof data.balance==='number'){setBalance(data.balance);if(won)playSound('win',sound)}};
  const claimReward=async()=>{if(rewardBusy||now<nextRewardAt)return;setRewardBusy(true);const response=await fetch('/api/wallet/claim-reward',{method:'POST'});const data=await response.json();if(response.ok){setBalance(data.balance);setNextRewardAt(data.nextRewardAt);playSound('win',sound)}else if(data.nextRewardAt)setNextRewardAt(data.nextRewardAt);setRewardBusy(false)};
  const runBotTurns=async(next:Card[],nextBots:BotPlayer[],dealerUp:Card)=>{for(let i=0;i<nextBots.length;i++){if(gameMode==='blood-duel'&&nextBots[i].blood<=0)continue;setTurnOwner(nextBots[i].id);setMessage(`${nextBots[i].name.toUpperCase()} OYNUYOR`);await new Promise(r=>setTimeout(r,650));while(botShouldHit(nextBots[i].hand,dealerUp)){nextBots[i]={...nextBots[i],hand:[...nextBots[i].hand,next.pop()!]};playSound('card',sound);setBots([...nextBots]);await new Promise(r=>setTimeout(r,500))}}setDeck(next);setTurnOwner('player');setMessage('SIRA SENDE')};
  const deal=async()=>{if(gameMode==='blood-duel'&&playerBlood<=0){setMessage('KANSIZLIKTAN ELENDİN • DÜELLOYU YENİDEN BAŞLAT');return}if(!bet){setMessage('ÖNCE BİR JETON SEÇ');return}let next=deck.length<24?freshDeck():[...deck];const p:Card[]=[],d:Card[]=[];let nextBots=bots.map(b=>({...b,hand:[]}));setPhase('playing');setTurnOwner(null);setPlayer([]);setSplitHand(null);setActiveHand(0);setHandBets([bet]);setInsuranceDelta(0);setDealer([]);setMessage('KARTLAR DAĞITILIYOR');for(let round=0;round<2;round++){p.push(next.pop()!);playSound('card',sound);setPlayer([...p]);await new Promise(r=>setTimeout(r,180));for(let i=0;i<nextBots.length;i++){if(gameMode==='blood-duel'&&nextBots[i].blood<=0)continue;nextBots[i]={...nextBots[i],hand:[...nextBots[i].hand,next.pop()!]};playSound('card',sound);setBots([...nextBots]);await new Promise(r=>setTimeout(r,150))}d.push({...next.pop()!,hidden:round===1});playSound('card',sound);setDealer([...d]);await new Promise(r=>setTimeout(r,180))}setDeck(next);if(d[0].rank==='A'){setInsuranceOffer(true);setMessage('KRUPİYE AS GÖSTERİYOR • SİGORTA?');return}await runBotTurns(next,nextBots,d[0])};
  const chooseInsurance=async(take:boolean)=>{const stake=handBets[0]/2;const dealerBlackjack=['10','J','Q','K'].includes(dealer[1].rank);const adjustment=take?(dealerBlackjack?stake*2:-stake):0;setInsuranceOffer(false);setInsuranceDelta(adjustment);if(dealerBlackjack){setTurnOwner('player');setTimeout(()=>finishDealer(dealer,deck,player,null,handBets,adjustment),50);return}await runBotTurns([...deck],bots.map(b=>({...b,hand:[...b.hand]})),dealer[0])};
  const finishDealer=(dh=dealer,cd=deck,ph=player,sh=splitHand,bets=handBets,insuranceAdj=insuranceDelta)=>{
    setTurnOwner(null);const nd=[...cd],next=dh.map(c=>({...c,hidden:false}));while(handValue(next)<17)next.push(nd.pop()!);setDealer(next);setDeck(nd);setPhase('result');
    const dealerTotal=handValue(next),dealerBJ=dealerTotal===21&&next.length===2;const hands=sh?[ph,sh]:[ph];let delta=insuranceAdj;const results:string[]=[];let naturalWin=false;
    hands.forEach((hand,i)=>{const pv=handValue(hand),wager=bets[i]||bets[0];const natural=!sh&&hand.length===2&&pv===21;if(pv>21){delta-=wager;results.push('YANDI')}else if(dealerBJ){if(natural)results.push('BERABERE');else{delta-=wager;results.push('KAYBETTİ')}}else if(natural){naturalWin=true;delta+=wager*1.5;results.push('BLACKJACK')}else if(dealerTotal>21||pv>dealerTotal){delta+=wager;results.push('KAZANDI')}else if(pv===dealerTotal)results.push('BERABERE');else{delta-=wager;results.push('KAYBETTİ')}});
    setBots(current=>{const updated=current.map(bot=>{if(gameMode==='blood-duel'&&bot.blood<=0)return bot;const value=handValue(bot.hand),natural=value===21&&bot.hand.length===2;let change=0;if(value>21)change=-25;else if(dealerBJ)change=natural?0:-25;else if(natural)change=37.5;else if(dealerTotal>21||value>dealerTotal)change=25;else if(value<dealerTotal)change=-25;const bloodLoss=gameMode==='blood-duel'&&change<0?(value>21?30:25):0;return{...bot,balance:bot.balance+change,blood:Math.max(0,bot.blood-bloodLoss)}});if(gameMode==='blood-duel'&&duelActive&&updated.length>0&&updated.every(bot=>bot.blood<=0))setTimeout(()=>{settleBloodDuel(true);setMessage(`KAN DÜELLOSUNU KAZANDIN • +${prizePool.toLocaleString('tr-TR')} JETON`)},0);return updated});
    playSound(delta>0?'win':delta<0?'lose':'chip',sound);recordGame(delta,delta>0?'win':delta<0?'loss':'push',naturalWin);let resultMessage=hands.length>1?`EL 1 ${results[0]} • EL 2 ${results[1]}`:results[0];if(gameMode==='blood-duel'&&delta<0){const damage=results.includes('YANDI')?30:25;const remaining=Math.max(0,playerBlood-damage);setPlayerBlood(remaining);if(remaining===0){settleBloodDuel(false);resultMessage=`KANSIZLIKTAN ELENDİN • ${prizePool.toLocaleString('tr-TR')} JETONLUK HAVUZU KAYBETTİN`}else resultMessage=`${resultMessage} • -${damage} KAN`;}setMessage(resultMessage)
  };
  const nextHandOrDealer=(nd=deck,first=player,second=splitHand)=>{if(second&&activeHand===0){setActiveHand(1);setMessage('İKİNCİ ELİN SIRASI');return}setTimeout(()=>finishDealer(dealer,nd,first,second,handBets),300)};
  const hit=()=>{if(onlineGame){socketRef.current?.emit('game:action',{action:'hit'});return}if(phase!=='playing'||turnOwner!=='player'||insuranceOffer)return;const nd=[...deck];if(activeHand===0){const np=[...player,nd.pop()!];setDeck(nd);setPlayer(np);if(handValue(np)>=21)nextHandOrDealer(nd,np,splitHand)}else if(splitHand){const ns=[...splitHand,nd.pop()!];setDeck(nd);setSplitHand(ns);if(handValue(ns)>=21)setTimeout(()=>finishDealer(dealer,nd,player,ns,handBets),300)}};
  const stand=()=>{if(onlineGame){socketRef.current?.emit('game:action',{action:'stand'});return}if(turnOwner!=='player'||insuranceOffer)return;nextHandOrDealer(deck,player,splitHand)};
  const double=()=>{const hand=activeHand===0?player:splitHand;if(phase!=='playing'||turnOwner!=='player'||!hand||hand.length!==2||balance<bet+(handBets[activeHand]||0))return;const nd=[...deck],extra=handBets[activeHand];const nextBets=handBets.map((b,i)=>i===activeHand?b*2:b);setHandBets(nextBets);setBet(b=>b+extra);if(activeHand===0){const np=[...player,nd.pop()!];setDeck(nd);setPlayer(np);if(splitHand){setActiveHand(1);setMessage('İKİNCİ ELİN SIRASI')}else setTimeout(()=>finishDealer(dealer,nd,np,null,nextBets),300)}else if(splitHand){const ns=[...splitHand,nd.pop()!];setDeck(nd);setSplitHand(ns);setTimeout(()=>finishDealer(dealer,nd,player,ns,nextBets),300)}};
  const split=()=>{if(turnOwner!=='player'||player.length!==2||splitHand||player[0].rank!==player[1].rank||balance<bet*2)return;const nd=[...deck],original=bet;const first=[player[0],nd.pop()!],second=[player[1],nd.pop()!];setDeck(nd);setPlayer(first);setSplitHand(second);setHandBets([original,original]);setBet(original*2);setActiveHand(0);setMessage(player[0].rank==='A'?'ASLAR BÖLÜNDÜ • TEK KART':'BİRİNCİ ELİN SIRASI');if(player[0].rank==='A')setTimeout(()=>finishDealer(dealer,nd,first,second,[original,original]),500)};
  const surrender=()=>{if(turnOwner!=='player'||player.length!==2||splitHand||insuranceOffer)return;setTurnOwner(null);setPhase('result');recordGame(-handBets[0]/2,'loss');playSound('lose',sound);if(gameMode==='blood-duel'){const remaining=Math.max(0,playerBlood-15);setPlayerBlood(remaining);setMessage(remaining===0?'KANIN TÜKENDİ • KANSIZLIKTAN ELENDİN':'TESLİM • -15 KAN')}else setMessage('TESLİM • BAHİSİN YARISI İADE')};
  const newRound=()=>{if(onlineGame){if(liveRoom?.leaderId===user.id)socketRef.current?.emit('game:next-round',{});else setMessage('YENİ ELİ MASA LİDERİ BAŞLATACAK');return}setPlayer([]);setSplitHand(null);setDealer([]);setBet(0);setHandBets([]);setInsuranceOffer(false);setInsuranceDelta(0);setActiveHand(0);setTurnOwner(null);setPhase('betting');setMessage('BAHİSLERİNİZİ YERLEŞTİRİN')};
  const addBot=()=>{if(bots.length>=4)return;const name=botNames.find(n=>!bots.some(b=>b.name===n))||`Bot ${bots.length+1}`;setBots(v=>[...v,{id:Date.now(),name,balance:110000+Math.floor(Math.random()*90000),initials:name[0],color:`linear-gradient(145deg,hsl(${Math.random()*360} 50% 50%),#17211d)`,hand:randomHand(),blood:100}])};
  const openBloodLobby=()=>{if(phase!=='betting'){setMessage('MODU DEĞİŞTİRMEK İÇİN ELİN BİTMESİNİ BEKLE');return}setDuelError('');setPanel('bloodLobby')};
  const createBloodDuel=async(stake:number)=>{if(duelBusy)return;setDuelBusy(true);setDuelError('');const participants=bots.length+1;try{const response=await fetch('/api/blood-duel/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stake,participants})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Düello açılamadı.');setBalance(data.balance);setDuelStake(stake);setPrizePool(data.prize);setDuelActive(true);setGameMode('blood-duel');setPlayerBlood(100);setBots(current=>current.map(bot=>({...bot,balance:Math.max(0,bot.balance-stake),blood:100})));setBet(0);setMessage(`KAN DÜELLOSU AÇILDI • ÖDÜL HAVUZU ${Number(data.prize).toLocaleString('tr-TR')}`);setPanel(null)}catch(e){setDuelError(e instanceof Error?e.message:'Bağlantı hatası.')}finally{setDuelBusy(false)}};
  const changeMode=(mode:GameMode)=>{if(mode==='blood-duel'){openBloodLobby();return}if(phase!=='betting')return;if(duelActive)settleBloodDuel(false);setGameMode('classic');setDuelStake(0);setPrizePool(0);setPlayerBlood(100);setBots(current=>current.map(bot=>({...bot,blood:100})));setMessage('KLASİK BLACKJACK')};
  const restartBloodDuel=()=>{setPlayerBlood(100);setBots(current=>current.map(bot=>({...bot,blood:100})));setGameMode('classic');setDuelStake(0);setPrizePool(0);newRound();setPanel('bloodLobby');setMessage('YENİ KAN DÜELLOSU İÇİN GİRİŞ SEVİYESİ SEÇ')};
  const roomAction=(event:'room:create'|'room:join'|'room:ready'|'room:start',payload:unknown={})=>{const socket=socketRef.current;if(!socket){setRoomError('Canlı masa bağlantısı hazırlanıyor, tekrar dene.');return}setRoomBusy(true);setRoomError('');const send=()=>socket.emit(event,payload,(reply:{ok:boolean;error?:string;room?:LiveRoom})=>{setRoomBusy(false);if(!reply.ok){setRoomError(reply.error||'İşlem başarısız.');return}if(reply.room){setLiveRoom(reply.room);history.replaceState({},'',`${location.pathname}?room=${reply.room.code}`)}});if(socket.connected)send();else socket.once('connect',send)};
  const sendChat=()=>{if(!chat.trim())return;setMessages(v=>[...v,{name:user.username,text:chat.trim(),mine:true}]);setChat('')};
  const copyInvite=async()=>{const code=liveRoom?.code||'7A2F';await navigator.clipboard.writeText(`${location.origin}?room=${code}`);setCopied(true);setTimeout(()=>setCopied(false),1800)};
  const submitAdjustment=async()=>{if(!adjustUser)return;const response=await fetch(`/api/admin/users/${adjustUser.id}/adjust`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount:Number(adjustAmount),reason:adjustReason})});const data=await response.json();if(response.ok){setAdminUsers(list=>list.map(u=>u.id===adjustUser.id?{...u,balance:data.balance}:u));setAdjustUser(null);setAdjustAmount('');setAdjustReason('')}else setMessage(data.error||'İŞLEM BAŞARISIZ')};
  const topUpMyAdminWallet=async(amount:number)=>{const response=await fetch(`/api/admin/users/${user.id}/adjust`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount,reason:'Admin kendi cüzdan yüklemesi'})});const data=await response.json();if(response.ok){setBalance(data.balance);setAdminUsers(list=>list.map(u=>u.id===user.id?{...u,balance:data.balance}:u));playSound('win',sound);setMessage(`ADMİN CÜZDANINA +${amount.toLocaleString('tr-TR')} EKLENDİ`)}};
  const rewardSeconds=Math.max(0,Math.ceil((nextRewardAt-now)/1000)),rewardClock=`${String(Math.floor(rewardSeconds/60)).padStart(2,'0')}:${String(rewardSeconds%60).padStart(2,'0')}`;

  return <main className={`app-shell theme-${theme} ${effects?'effects-on':''} ${chatOpen?'':'chat-closed'} ${turnOwner==='player'?'your-turn':''} mode-${gameMode}`} style={{'--felt':colors[0],'--accent':colors[1]} as React.CSSProperties}>
    <header className="topbar"><a className="brand"><Crown size={23}/><span>BLOODYJACK</span><small>PRIVATE BLACKJACK CLUB</small></a><nav><button className="nav-active">MASA</button><button onClick={()=>setPanel('onlineLobby')}>ONLINE MASA</button><button onClick={()=>setPanel('friends')}>ARKADAŞLAR</button><button onClick={()=>setPanel('rules')}>KURALLAR & SSS</button>{user.role==='admin'&&<button onClick={()=>setPanel('admin')}>ADMİN</button>}</nav><div className="header-actions"><button title="Sesi aç/kapat" onClick={()=>setSound(!sound)} className={!sound?'muted':''}><Volume2/></button><button title="Sohbeti aç/kapat" onClick={()=>setChatOpen(!chatOpen)}><MessageCircle/></button><button title="Ayarlar" onClick={()=>setPanel('settings')}><Settings/></button><button className="wallet" onClick={()=>setPanel('profile')}><span>{user.username}</span><strong>◉ {balance.toLocaleString('tr-TR')}</strong></button><button className="exit" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});setUser(null)}}><LogOut size={17}/> Çıkış</button></div></header>
    <section className="game-area"><div className="room-row"><button className="room-badge" onClick={()=>setPanel('onlineLobby')}><span className="live-dot"/> {liveRoom?'ONLINE MASA':'ÖZEL MASA'} <b>#{liveRoom?.code||'YEREL'}</b><em>•</em><Users size={14}/> {liveRoom?.players.length||bots.length+1} / 5</button><div className="mode-switch"><button className={gameMode==='classic'?'selected':''} onClick={()=>changeMode('classic')}>KLASİK</button><button className={gameMode==='blood-duel'?'selected blood':''} onClick={()=>changeMode('blood-duel')}><Droplets/> KAN DÜELLOSU</button></div>{duelActive&&<div className="duel-pot"><Droplets/><span>ÖDÜL HAVUZU</span><b>◉ {prizePool.toLocaleString('tr-TR')}</b></div>}<button className={`reward-pill ${rewardSeconds===0?'ready':''}`} onClick={claimReward} disabled={rewardBusy||rewardSeconds>0}><Sparkles/> {rewardSeconds===0?'25 JETONU AL':`HEDİYE ${rewardClock}`}</button><button className="invite-pill" onClick={()=>setPanel('onlineLobby')}><UserPlus/> ARKADAŞ DAVET ET</button></div>
      <div className="table-wrap three-table"><Suspense fallback={<div className="canvas-loading"/>}><BloodyTable3D active={turnOwner==='player'}/></Suspense><div className="ambient ambient-one"/><div className="ambient ambient-two"/><div className="table-depth"><div className="table-rail"><div className="table-felt"><div className="dealer-zone"><div className="dealer-title"><span>KRUPİYE</span>{dealer.length>0&&<b>{phase==='playing'?'?':dealerValue}</b>}</div><div className="cards">{dealer.map((c,i)=><PlayingCard card={c} index={i} key={i}/>)}</div></div><div className="table-mark"><Crown/><b>BLOODYJACK</b><span>BLACKJACK PAYS 3 TO 2</span><small>DEALER STANDS ON 17</small></div>
        <div className="rivals">{bots.map((bot,i)=><div className={`rival-slot rival-${i}`} key={bot.id}><PlayerSeat bot={bot} active={turnOwner===bot.id} playing={phase!=='betting'&&bot.blood>0} bloodMode={gameMode==='blood-duel'} onRemove={()=>setBots(v=>v.filter(b=>b.id!==bot.id))}/></div>)}</div>
        {bots.length<4&&<button className="empty-seat" onClick={addBot}><span><Plus/></span><small>BOT EKLE</small></button>}
        <div className={`player-zone ${splitHand?'split-zone':''}`}><div className={`player-hand ${activeHand===0?'active-player-hand':''}`}><div className="cards">{player.map((c,i)=><PlayingCard card={c} index={i} key={i}/>)}</div>{player.length>0&&<span className={`score ${playerValue>21?'bust':''}`}>{playerValue}</span>}{splitHand&&<small>EL 1 • {handBets[0]}</small>}</div>{splitHand&&<div className={`player-hand ${activeHand===1?'active-player-hand':''}`}><div className="cards">{splitHand.map((c,i)=><PlayingCard card={c} index={i} key={i}/>)}</div><span className={`score ${splitValue>21?'bust':''}`}>{splitValue}</span><small>EL 2 • {handBets[1]}</small></div>}{bet>0&&<div className="bet-stack"><i/><i/><i/><b>{bet}</b></div>}{gameMode==='blood-duel'&&<div className={`player-blood ${playerBlood<=0?'empty':''}`}><Droplets/><span><i style={{width:`${playerBlood}%`}}/></span><b>{playerBlood} KAN</b></div>}</div>
      </div></div></div></div>
      <div className={`status ${phase==='result'?'result':''}`}><span>{message}</span></div><div className="controls glass-controls"><div className="chip-tray">{chips.map((c,i)=><button key={c} onClick={()=>addBet(c)} disabled={phase!=='betting'||(gameMode==='blood-duel'&&playerBlood<=0)} className={`chip chip-${i}`}><span>{c}</span></button>)}<div className="bet-total"><span>TOPLAM BAHİS</span><b>◉ {bet}</b></div></div><div className="game-buttons">{phase==='betting'&&gameMode==='blood-duel'&&playerBlood<=0?<button className="primary wide" onClick={restartBloodDuel}>DÜELLOYU YENİDEN BAŞLAT</button>:phase==='betting'&&<><button className="subtle" onClick={()=>setBet(0)}>TEMİZLE</button><button className="primary" onClick={deal}>DAĞIT</button></>}{phase==='playing'&&insuranceOffer&&!onlineGame&&<><button className="subtle" onClick={()=>chooseInsurance(false)}>SİGORTASIZ DEVAM</button><button className="primary" disabled={balance<bet+handBets[0]/2} onClick={()=>chooseInsurance(true)}>SİGORTA • {handBets[0]/2}</button></>}{phase==='playing'&&!insuranceOffer&&<><button className="surrender" onClick={surrender} disabled={!!onlineGame||turnOwner!=='player'||player.length!==2||!!splitHand}>TESLİM</button><button className="split" onClick={split} disabled={!!onlineGame||turnOwner!=='player'||player.length!==2||!!splitHand||player[0]?.rank!==player[1]?.rank||balance<bet*2}>İKİYE BÖL</button><button className="subtle" onClick={double} disabled={!!onlineGame||turnOwner!=='player'||(activeHand===0?player.length:splitHand?.length)!==2}>İKİYE KATLA</button><button className="stand" disabled={turnOwner!=='player'} onClick={stand}>BEKLE</button><button className="primary" disabled={turnOwner!=='player'} onClick={hit}>KART ÇEK</button></>}{phase==='result'&&<button className="primary wide" disabled={!!onlineGame&&liveRoom?.leaderId!==user.id} onClick={newRound}>{onlineGame&&liveRoom?.leaderId!==user.id?'LİDER BEKLENİYOR':'YENİ EL'}</button>}</div></div>
    </section>
    <aside className="chat"><div className="chat-head"><span><MessageCircle size={17}/> MASA SOHBETİ</span><button onClick={()=>setChatOpen(false)} title="Sohbeti kapat"><X/></button></div><div className="messages">{messages.map((m,i)=><p className={m.mine?'mine':''} key={i}><b>{m.name}</b><span>{m.text}</span></p>)}</div><div className="chat-input"><input value={chat} onChange={e=>setChat(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} placeholder="Mesaj yaz..."/><button onClick={sendChat}>GÖNDER</button></div></aside>

    {(panel==='invite'||panel==='onlineLobby')&&<Modal title="ONLINE MASA LOBİSİ" icon={<Users/>} close={()=>setPanel(null)}><div className="modal-body online-lobby">{!liveRoom?<><p className="modal-copy">Yeni masa kurup bağlantıyı paylaş veya arkadaşının gönderdiği altı karakterli oda koduyla katıl.</p><button className="modal-primary" disabled={roomBusy} onClick={()=>roomAction('room:create')}>YENİ ONLINE MASA KUR</button><div className="join-divider"><span>VEYA ODA KODU</span></div><div className="room-join"><input maxLength={6} value={roomCodeInput} onChange={e=>setRoomCodeInput(e.target.value.toUpperCase().replace(/[^A-F0-9]/g,''))} placeholder="A1B2C3"/><button disabled={roomBusy||roomCodeInput.length!==6} onClick={()=>roomAction('room:join',{code:roomCodeInput})}>KATIL</button></div></>:<><div className="invite-code"><span>CANLI MASA KODU</span><b>{liveRoom.code}</b></div><button className="modal-secondary" onClick={copyInvite}>{copied?<><Check/> DAVET LİNKİ KOPYALANDI</>:<><Copy/> DAVET LİNKİNİ KOPYALA</>}</button><div className="live-player-list">{liveRoom.players.map(p=><div key={p.id} className={!p.online?'offline':''}><div className="avatar">{p.username[0].toUpperCase()}</div><span><b>{p.username}{p.id===liveRoom.leaderId&&<em> LİDER</em>}</b><small>{p.online?(p.id===liveRoom.leaderId?'Masa sahibi':p.ready?'Hazır':'Bekleniyor'):'Bağlantı koptu'}</small></span><i className={p.ready||p.id===liveRoom.leaderId?'ready':''}/></div>)}</div>{user.id!==liveRoom.leaderId?<button className="modal-primary" onClick={()=>roomAction('room:ready')}>{liveRoom.players.find(p=>p.id===user.id)?.ready?'HAZIR DEĞİLİM':'HAZIRIM'}</button>:<button className="modal-primary" disabled={roomBusy||liveRoom.players.length<2} onClick={()=>roomAction('room:start')}>OYUNU BAŞLAT</button>}</>}{roomError&&<div className="auth-error">{roomError}</div>}</div></Modal>}
    {panel==='bloodLobby'&&<Modal title="KAN DÜELLOSU • MASA KUR" icon={<Droplets/>} close={()=>setPanel(null)}><div className="modal-body blood-lobby"><p className="modal-copy">Masa lideri giriş seviyesini seçer. Masadaki herkes aynı jetonu havuza koyar; kanı kalan son yarışmacı büyük ödülün tamamını alır.</p><div className="duel-tiers">{[{stake:10000,label:'KIZIL ODA',tone:'low'},{stake:50000,label:'KAN MAHZENİ',tone:'mid'},{stake:100000,label:'SON DAMLA',tone:'high'}].map(t=><button key={t.stake} className={t.tone} disabled={duelBusy||balance<t.stake} onClick={()=>createBloodDuel(t.stake)}><Droplets/><span>{t.label}</span><b>◉ {t.stake.toLocaleString('tr-TR')}</b><small>{bots.length+1} OYUNCU • ÖDÜL ◉ {(t.stake*(bots.length+1)).toLocaleString('tr-TR')}</small>{balance<t.stake&&<em>YETERSİZ JETON</em>}</button>)}</div>{duelError&&<div className="auth-error">{duelError}</div>}<div className="duel-lobby-footer"><span>SENİN BAKİYEN</span><b>◉ {balance.toLocaleString('tr-TR')}</b></div></div></Modal>}
    {panel==='friends'&&<Modal title="ARKADAŞLAR & BOTLAR" icon={<Users/>} close={()=>setPanel(null)}><div className="modal-body"><div className="friend-list">{bots.map(b=><div key={b.id}><div className="avatar" style={{background:b.color}}>{b.initials}</div><span><b>{b.name}</b><small>Masada • Bot oyuncu</small></span><button onClick={()=>setBots(v=>v.filter(x=>x.id!==b.id))}><Trash2/></button></div>)}</div><button className="modal-primary" onClick={addBot} disabled={bots.length>=4}><Bot/> {bots.length>=4?'MASA DOLU':'YENİ BOT EKLE'}</button><button className="modal-secondary" onClick={()=>setPanel('invite')}><UserPlus/> GERÇEK ARKADAŞ DAVET ET</button></div></Modal>}
    {panel==='rules'&&<Modal title="OYUN KURALLARI & SSS" icon={<BookOpen/>} close={()=>setPanel(null)}><div className="modal-body rules-body"><div className="rule-summary"><div><b>3:2</b><span>BLACKJACK</span></div><div><b>17</b><span>KRUPİYE BEKLER</span></div><div><b>2:1</b><span>SİGORTA</span></div></div><details open><summary>Nasıl kazanırım?</summary><p>21'i geçmeden krupiyeden yüksek bir el yap. Krupiye 21'i aşarsa yanmamış bütün eller kazanır. Eşitlikte bahis değişmez.</p></details><details><summary>Kan Düellosu nasıl çalışır?</summary><p>Herkes 100 kanla başlar. El kaybı 25, 21'i aşarak yanmak 30, teslim olmak 15 kan götürür. Kanı sıfırlanan yarışmacı kansızlıktan elenir ve sonraki ellerde kart almaz. Jeton sonucu klasik Blackjack ile aynı anda işlemeye devam eder.</p></details><details><summary>Kart değerleri nedir?</summary><p>2–10 üzerindeki değer kadardır. J, Q ve K 10 sayılır. As, eli yakmayan şekilde 1 veya 11 değerindedir.</p></details><details><summary>İkiye bölme nasıl çalışır?</summary><p>Aynı değerdeki ilk iki kart iki ayrı ele ayrılır ve eşit ikinci bahis konur. Her el sırayla oynanır. Bölünmüş aslara yalnızca bir kart verilir.</p></details><details><summary>İkiye katlama nedir?</summary><p>İlk iki kartta el bahsini iki katına çıkarırsın; yalnızca bir kart alır ve otomatik beklersin.</p></details><details><summary>Sigorta ve teslim nedir?</summary><p>Krupiye as gösterdiğinde sigorta, ana bahsin yarısıdır ve krupiye blackjack yaparsa 2:1 öder. Teslim ilk iki kartta bahsin yarısını kaybederek eli kapatır.</p></details><details><summary>Botlar hile yapıyor mu?</summary><p>Hayır. Tüm kartlar aynı karıştırılmış desteden sırayla çıkar. Botlar krupiyenin açık kartına göre temel hit/bekle stratejisi uygular ve bakiyeleri sonuçta artar veya azalır.</p></details></div></Modal>}
    {panel==='profile'&&<Modal title="OYUNCU PROFİLİ & İSTATİSTİKLER" icon={<Crown/>} close={()=>setPanel(null)}><div className="modal-body profile-body"><div className="profile-hero"><div className="avatar">{user.username[0].toUpperCase()}</div><span><b>{user.username}</b><small>{user.email}</small></span><strong>◉ {balance.toLocaleString('tr-TR')}</strong></div>{stats&&<><div className="profile-stats"><div><span>TOPLAM EL</span><b>{stats.hands}</b></div><div><span>KAZANMA</span><b>%{stats.win_rate}</b></div><div><span>BLACKJACK</span><b>{stats.blackjacks}</b></div><div><span>BRÜT KAZANÇ</span><b>{stats.gross_winnings.toLocaleString('tr-TR')}</b></div><div><span>TOPLAM BAHİS</span><b>{stats.total_wagered.toLocaleString('tr-TR')}</b></div><div className={stats.net_profit>=0?'positive':'negative'}><span>NET KAZANÇ</span><b>{stats.net_profit>=0?'+':''}{stats.net_profit.toLocaleString('tr-TR')}</b></div></div><div className="record-line"><span>En büyük tek-el kazancı</span><b>◉ {stats.biggest_win.toLocaleString('tr-TR')}</b></div><div className="record-line"><span>Kazanma / Kaybetme / Beraberlik</span><b>{stats.wins} / {stats.losses} / {stats.pushes}</b></div></>}</div></Modal>}
    {panel==='settings'&&<Modal title="MASA AYARLARI" icon={<Settings/>} close={()=>setPanel(null)}><div className="modal-body settings-body"><h4>MASA TEMASI</h4><div className="theme-grid">{Object.entries(themes).map(([key,c])=><button className={theme===key?'selected':''} key={key} onClick={()=>setTheme(key as keyof typeof themes)} style={{background:`linear-gradient(135deg,${c[0]},${c[1]})`}}><Check/>{key.toUpperCase()}</button>)}</div><div className="setting-row"><span><Volume2/><b>Oyun sesleri</b></span><button className={`toggle ${sound?'on':''}`} onClick={()=>setSound(!sound)}><i/></button></div><div className="setting-row"><span><Sparkles/><b>Parlama efektleri</b></span><button className={`toggle ${effects?'on':''}`} onClick={()=>setEffects(!effects)}><i/></button></div></div></Modal>}
    {panel==='admin'&&user.role==='admin'&&<Modal title="ADMİN • KULLANICI CÜZDANLARI" icon={<ShieldCheck/>} close={()=>{setPanel(null);setAdjustUser(null)}}><div className="modal-body admin-body admin-users-body"><div className="admin-success"><ShieldCheck/><span><b>Sunucu tarafından doğrulandı</b><small>Her değişiklik işlem geçmişine kaydedilir.</small></span></div>{!adjustUser?<><div className="self-topup"><span><b>KENDİ ADMİN CÜZDANIN</b><small>Mevcut: ◉ {balance.toLocaleString('tr-TR')}</small></span><button onClick={()=>topUpMyAdminWallet(1000)}>+1.000</button><button onClick={()=>topUpMyAdminWallet(10000)}>+10.000</button></div><h4>KULLANICI SEÇ</h4><div className="admin-user-list">{adminUsers.map(u=><button key={u.id} onClick={()=>setAdjustUser(u)}><div className="avatar">{u.username[0].toUpperCase()}</div><span><b>{u.username}{u.role==='admin'&&<em> ADMIN</em>}</b><small>{u.email} • {u.hands||0} el</small></span><strong>◉ {Number(u.balance).toLocaleString('tr-TR')}</strong><ChevronRight/></button>)}</div></>:<div className="adjust-form"><button className="back-link" onClick={()=>setAdjustUser(null)}>← Kullanıcılara dön</button><div className="profile-hero"><div className="avatar">{adjustUser.username[0].toUpperCase()}</div><span><b>{adjustUser.username}</b><small>Mevcut bakiye</small></span><strong>◉ {Number(adjustUser.balance).toLocaleString('tr-TR')}</strong></div><label>JETON MİKTARI<input type="number" value={adjustAmount} onChange={e=>setAdjustAmount(e.target.value)} placeholder="Örn. 500 veya -250"/></label><label>İŞLEM AÇIKLAMASI<input value={adjustReason} onChange={e=>setAdjustReason(e.target.value)} placeholder="Neden ekleniyor/çıkarılıyor?"/></label><button className="modal-primary" disabled={!Number(adjustAmount)||adjustReason.trim().length<3} onClick={submitAdjustment}>İŞLEMİ KAYDET</button></div>}</div></Modal>}
  </main>;
}

createRoot(document.getElementById('root')!).render(<App/>);
